########## extract()

extract <- function(x, ...) cat("Data extraction not defined for this class:",class(x),"\n")

setGeneric("extract", function(x, ...) standardGeneric("extract"))

setMethod("extract","aws",function(x, what="y"){
  what <- tolower(what) 
  z <- list(NULL)
  if("y" %in% what) z$y <- x@y
  if("yhat" %in% what) z$yhat <- if(x@degree==0) drop(x@theta) else x@theta
  if("x" %in% what) z$x <- x@x
  if("sigma2" %in% what) z$sigma2 <- x@sigma2
  if("ni" %in% what) z$ni <- x@ni
  if("mask" %in% what) z$mask <- x@mask
  invisible(z)
})
setMethod("extract","awssegment",function(x, what="y"){
  what <- tolower(what) 
  z <- list(NULL)
  if("y" %in% what) z$y <- x@y
  if("yhat" %in% what) z$yhat <- drop(x@theta) 
  if("segment" %in% what) z$segment <- x@segment
  if("x" %in% what) z$x <- x@x
  if("sigma2" %in% what) z$sigma2 <- x@sigma2
  if("ni" %in% what) z$ni <- x@ni
  if("mask" %in% what) z$mask <- x@mask
  invisible(z)
})
setMethod("extract","kernsm",function(x, what="y"){
  what <- tolower(what) 
  z <- list(NULL)
  if("y" %in% what) z$y <- x@y
  if("yhat" %in% what) z$yhat <- x@yhat
  if("vred" %in% what) z$vred <- x@vred
  if("vhat" %in% what) z$vhat <- (median(abs(x@y[-1]-x@y[-n]))/.9538)^2/x@vred
  invisible(z)
})
setMethod("extract","ICIsmooth",function(x, what="y"){
  what <- tolower(what) 
  z <- list(NULL)
  if("y" %in% what) z$y <- x@y
  if("yhat" %in% what) z$yhat <- x@yhat
  if("vhat" %in% what) z$vhat <- x@vhat
  if("vred" %in% what) z$vred <- x@sigma^2/x@vhat
  if("hbest" %in% what) z$hbest <- x@hbest
  invisible(z)
})
################################################################
#                                                              #
# Section for summary(), print(), plot() functions (generic)   #
#                                                              #
################################################################

setMethod("print", "aws",
function(x){
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    cat("  Dimension            :", paste(x@dy, collapse="x"), "\n")
    cat("  Max. Bandwidth       :", x@hmax, "  degree=",x@degree,"\n")
    cat("  Lambda               :", x@lambda, "  (ladj=",x@ladj,")\n")
    cat("  Slots", slotNames(x), "\n")
    invisible(NULL)
})
setMethod("summary", "aws",
function(object, ...){
    cat("  Object of class", class(object),"\n")
    cat("  Generated by calls   :\n")
    print(object@call)
    cat("  Dimension            :", paste(object@dy, collapse="x"), "\n")
    cat("  Max. Bandwidth       :", object@hmax, "  degree=",object@degree,"\n")
    cat("  Lambda               :", object@lambda, "  (ladj=",object@ladj,")\n")
    cat("  mean sum of weights  :", mean(object$ni), "\n")
    cat("\n")
    invisible(NULL)
})
setMethod("plot", "aws",
function(x, what="yhat", col=grey(0:255/255),zind=NULL){
    if(!(what%in%c("data","yhat","ni","mask"))){
       warning("illegal value of what")
       return(invisible(NULL))
    }
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    d <- length(x@dy)
    img <- extract(x,what)
    if(d==3) {
       if(is.null(zind)) zind <- 1:x@dy[3]
       nview <- length(zind)
       nv1 <- as.integer(sqrt((nview+2)/1.5))
       nv2 <- ((nview+nv1-1)%/%nv1)
       par(mfrow=c(nv1,nv2),mar=c(2,2,2,.1),mgp=c(1,,1,0))
       for(i in zind){
          image(img[,,i],col=col)
          title(paste("slice",i))
       }
    } 
    if(d==2){
       image(img,col=col)
       title(switch(what,"data"="data","yhat"=paste("aws hmax=",x@hmax),
                         "ni"="sum of weights","mask"="mask"))   
    } 
    if(d==1){
       if("what"%in%c("data","yhat")){
           plot(x@y)
           lines(x@theta[,1])
           title(paste("Data and AWS for hmax=",x@hmax))
       } else {
           plot(img)
           title(switch(what,"ni"="sum of weights","mask"="mask"))   
       }
    }
    invisible(NULL)
})
setMethod("print", "awssegment",
function(x){
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    cat("  Dimension            :", paste(x@dy, collapse="x"), "\n")
    cat("  Max. Bandwidth       :", x@hmax,"\n")
    cat("  Lambda               :", x@lambda, "  (ladj=",x@ladj,")\n")
    cat("  Slots", slotNames(x), "\n")
    invisible(NULL)
})
setMethod("summary", "awssegment",
function(object, ...){
    cat("  Object of class", class(object),"\n")
    cat("  Generated by calls   :\n")
    print(object@call)
    cat("  Dimension            :", paste(object@dy, collapse="x"), "\n")
    cat("  Max. Bandwidth       :", object@hmax,"\n")
    cat("  Lambda               :", object@lambda, "  (ladj=",object@ladj,")\n")
    cat("  Size of segments:     ", paste(c("-1:","0:","1:"),table(object@segment)),"\n")
    cat("  mean sum of weights  :", mean(object$ni), "\n")
    cat("\n")
    invisible(NULL)
})


setMethod("plot", "awssegment",
function(x, what="yhat", col=grey(0:255/255),zind=NULL){
    if(!(what%in%c("data","yhat","ni","mask","segment"))){
       warning("illegal value of what")
       return(invisible(NULL))
    }
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    d <- length(x@dy)
    img <- extract(x,what)
    if(d==3) {
       if(is.null(zind)) zind <- 1:x@dy[3]
       nview <- length(zind)
       nv1 <- as.integer(sqrt((nview+2)/1.5))
       nv2 <- ((nview+nv1-1)%/%nv1)
       par(mfrow=c(nv1,nv2),mar=c(2,2,2,.1),mgp=c(1,,1,0))
       for(i in zind){
          image(img[,,i],col=col)
          title(paste("slice",i))
       }
    } 
    if(d==2){
       image(img,col=col)
       title(switch(what,"data"="data","yhat"=paste("awssegm hmax=",x@hmax),
                         "ni"="sum of weights","mask"="mask","segment"="segments"))   
    } 
    if(d==1){
       if("what"%in%c("data","yhat")){
           plot(x@y)
           lines(x@theta[,1])
           title(paste("Data and AWS for hmax=",x@hmax))
       } else {
           plot(img)
           title(switch(what,"ni"="sum of weights","mask"="mask","segment"="segments"))   
       }
    }
    invisible(NULL)
})
setMethod("print", "kernsm",
function(x){
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    cat("  Dimension            :", paste(x@dy, collapse="x"), "\n")
    cat("  Bandwidth            :", x@h,"\n")
    cat("  Slots", slotNames(x), "\n")
    invisible(NULL)
})
setMethod("summary", "kernsm",
function(object, ...){
    cat("  Object of class", class(object),"\n")
    cat("  Generated by calls   :\n")
    print(object@call)
    cat("  Dimension            :", paste(object@dy, collapse="x"), "\n")
    cat("  Bandwidth            :", object@h, "  derivatives=",object@m,"\n")
    cat("  Variance reduction   :", mean(object$vred), "\n")
    cat("\n")
    invisible(NULL)
})
setMethod("plot", "kernsm",
function(x, what="yhat", col=grey(0:255/255),zind=NULL){
    if(!(what%in%c("data","yhat","vred"))){
       warning("illegal value of what")
       return(invisible(NULL))
    }
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    d <- length(x@dy)
    img <- extract(x,what)
    if(d==3) {
       if(is.null(zind)) zind <- 1:x@dy[3]
       nview <- length(zind)
       nv1 <- as.integer(sqrt((nview+2)/1.5))
       nv2 <- ((nview+nv1-1)%/%nv1)
       par(mfrow=c(nv1,nv2),mar=c(2,2,2,.1),mgp=c(1,,1,0))
       for(i in zind){
          image(img[,,i],col=col)
          title(paste("slice",i))
       }
    } 
    if(d==2){
       image(img,col=col)
       title(switch(what,"data"="data","yhat"=paste("ksmooth h=",x@h),
                         "vred"="variance reduction"))   
    } 
    if(d==1){
       if("what"%in%c("data","yhat")){
           plot(x@y)
           lines(x@theta[,1])
           title(paste("Data and kernsm for h=",x@h))
       } else {
           plot(img)
           title(switch(what,"vred"="variance reduction"))   
       }
    }
    invisible(NULL)
})
setMethod("print", "ICIsmooth",
function(x){
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    cat("  Dimension            :", paste(x@dy, collapse="x"), "\n")
    cat("  Bandwidth            :", x@hmax," hinc:",x@hinc,"\n")
    cat("  Threshold            :", x@thresh,"\n")
    if(x@nsector>1)
    cat("  # of sectors          :", x@nsector, if(x@sector>0) paste("sector", x@sector),
        "symmetric:",x@symmetric,"\n")
    cat("  Slots", slotNames(x), "\n")
    invisible(NULL)
})
setMethod("summary", "ICIsmooth",
function(object, ...){
    cat("  Object of class", class(object),"\n")
    cat("  Generated by calls   :\n")
    print(object@call)
    cat("  Dimension            :", paste(object@dy, collapse="x"), "\n")
    cat("  Bandwidth            :", object@hmax,"  hinc:",object@hinc, "  derivatives=",object@m,"\n")
    cat("  Threshold            :", object@thresh,"\n")
    if(object@nsector>1)
    cat("  # of sectors          :", object@nsector, if(object@sector>0) paste("sector", 
           object@sector),"symmetric:",object@symmetri,"\n")
    cat("  Mean variance         :", mean(object$vhat), "\n")
    cat("\n")
    invisible(NULL)
})
setMethod("plot", "ICIsmooth",
function(x, what="yhat", col=grey(0:255/255),zind=NULL){
    if(!(what%in%c("data","yhat","vhat","vred","hbest"))){
       warning("illegal value of what")
       return(invisible(NULL))
    }
    cat("  Object of class", class(x),"\n")
    cat("  Generated by calls   :\n")
    print(x@call)
    d <- length(x@dy)
    img <- extract(x,what)
    if(d==3) {
       if(is.null(zind)) zind <- 1:x@dy[3]
       nview <- length(zind)
       nv1 <- as.integer(sqrt((nview+2)/1.5))
       nv2 <- ((nview+nv1-1)%/%nv1)
       par(mfrow=c(nv1,nv2),mar=c(2,2,2,.1),mgp=c(1,,1,0))
       for(i in zind){
          cat("displaying",switch(what,"data"="data","yhat"=paste("ksmooth h=",x@h),
                         "vhat"="variance","vred"="variance reduction",
                         "hbest"="optimal bandwidth"),"for ICIsmooth")
          image(img[,,i],col=col)
          title(paste("slice",i))
       }
    } 
    if(d==2){
       image(img,col=col)
       title(switch(what,"data"="data","yhat"=paste("ICIsmooth h=",x@h),
                         "vhat"="variance","vred"="variance reduction",
                         "hbest"="optimal bandwidth"))   
    } 
    if(d==1){
       if("what"%in%c("data","yhat")){
           plot(x@y)
           lines(x@theta[,1])
           title(paste("Data and ICIsmooth for h=",x@h))
       } else {
           plot(img)
           title(switch(what,"vhat"="variance","vred"="variance reduction",
                             "hbest"="optimal bandwidth"))   
       }
    }
    invisible(NULL)
})
